/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/coolroom3.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.36}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-22.75, 0.47, 10.79]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.09, 0.07, 0.09]}
          >
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials.concreto2}
            />
          </group>
          <group
            position={[-22.75, 0.47, 10.79]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.09, 0.07, 0.09]}
          >
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <group
            position={[-22.75, 0.47, 10.79]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.09, 0.07, 0.09]}
          >
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials["Iron01.001"]}
            />
          </group>
          <group
            position={[-22.75, 0.47, 10.79]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.09, 0.07, 0.09]}
          >
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials.piso}
            />
          </group>
          <group
            position={[-22.75, 0.47, 10.79]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.09, 0.07, 0.09]}
          >
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials.concrete3}
            />
          </group>
        </group>
      </group>
      <group
        position={[1.17, 0.02, 3.55]}
        rotation={[-Math.PI / 2, 0, -0.84]}
        scale={0.32}
      >
        <mesh geometry={nodes.Mesh_0.geometry} material={materials["1041"]} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials["1042"]} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials["1043"]} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials["1053"]} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials["1054"]} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials["1055"]} />
        <mesh geometry={nodes.Mesh_6.geometry} material={materials["1045"]} />
      </group>
      <group
        position={[14.24, 1.02, -4.03]}
        rotation={[-1.57, -1.56, 0]}
        scale={[0, 0, 0]}
      >
        <mesh
          geometry={nodes.Material2.geometry}
          material={materials.material_1}
        />
        <mesh
          geometry={nodes.Material2001.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Material2003.geometry}
          material={materials.material_11}
        />
        <mesh
          geometry={nodes.Material3.geometry}
          material={materials.material_3}
        />
        <mesh
          geometry={nodes.Material3001.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Material3002.geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes.Material3003.geometry}
          material={materials.material_7}
        />
        <mesh
          geometry={nodes.Material3004.geometry}
          material={materials.material_6}
        />
        <mesh
          geometry={nodes.Material3005.geometry}
          material={materials.material_10}
        />
        <mesh
          geometry={nodes.Material3006.geometry}
          material={materials.material_8}
        />
      </group>
      <group
        position={[0.43, 1, 1.09]}
        rotation={[-Math.PI / 2, 0, -1]}
        scale={[0.04, 0.04, 0.04]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.back2_aiStandardSurface1_0.geometry}
            material={nodes.back2_aiStandardSurface1_0.material}
          />
          <mesh
            geometry={nodes.back_bone_aiStandardSurface1_0.geometry}
            material={nodes.back_bone_aiStandardSurface1_0.material}
          />
          <mesh
            geometry={nodes.adjustment_aiStandardSurface1_0.geometry}
            material={nodes.adjustment_aiStandardSurface1_0.material}
          />
          <group
            position={[-1.7, -9.01, -0.19]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.19, 0.05, 0.19]}
          >
            <mesh
              geometry={nodes.Bolt_aiStandardSurface1_0.geometry}
              material={nodes.Bolt_aiStandardSurface1_0.material}
            />
          </group>
          <group
            position={[-1.38, -9.26, -1.91]}
            rotation={[0, 0, 1.44]}
            scale={[0.12, 0.06, 0.12]}
          >
            <mesh
              geometry={nodes.Bolt1_aiStandardSurface1_0.geometry}
              material={nodes.Bolt1_aiStandardSurface1_0.material}
            />
          </group>
          <group
            position={[0.62, -9.26, -1.91]}
            rotation={[0, 0, 1.69]}
            scale={[0.12, 0.06, 0.12]}
          >
            <mesh
              geometry={nodes.Bolt2_aiStandardSurface1_0.geometry}
              material={nodes.Bolt2_aiStandardSurface1_0.material}
            />
          </group>
          <group
            position={[0.97, -9.01, -0.19]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.19, 0.05, 0.19]}
          >
            <mesh
              geometry={nodes.Bolt3_aiStandardSurface1_0.geometry}
              material={nodes.Bolt3_aiStandardSurface1_0.material}
            />
          </group>
          <group
            position={[1.12, -9.45, 1.61]}
            rotation={[0.78, -0.04, 2.35]}
            scale={[0.03, 1.25, 0.74]}
          >
            <mesh
              geometry={nodes.pCube6_aiStandardSurface1_0.geometry}
              material={nodes.pCube6_aiStandardSurface1_0.material}
            />
          </group>
          <mesh
            geometry={nodes.pCube9_aiStandardSurface1_0.geometry}
            material={nodes.pCube9_aiStandardSurface1_0.material}
          />
          <group
            position={[-0.44, -9.59, 1.61]}
            rotation={[-0.17, 0, 0]}
            scale={0.65}
          >
            <mesh
              geometry={nodes.pCylinder10_aiStandardSurface1_0.geometry}
              material={nodes.pCylinder10_aiStandardSurface1_0.material}
            />
          </group>
          <group
            position={[-0.72, -0.43, -2]}
            rotation={[2.97, 0, 0]}
            scale={[-1, -1, -1]}
          >
            <mesh
              geometry={nodes.pCylinder14_aiStandardSurface1_0.geometry}
              material={nodes.pCylinder14_aiStandardSurface1_0.material}
            />
          </group>
          <group position={[-0.19, 0.08, 0.36]} scale={[1.96, 1, 1]}>
            <mesh
              geometry={nodes.polySurface11_aiStandardSurface1_0.geometry}
              material={nodes.polySurface11_aiStandardSurface1_0.material}
            />
          </group>
          <mesh
            geometry={nodes.pPlane3_aiStandardSurface1_0.geometry}
            material={nodes.pPlane3_aiStandardSurface1_0.material}
          />
          <mesh
            geometry={nodes.butt_aiStandardSurface1_0.geometry}
            material={nodes.butt_aiStandardSurface1_0.material}
          />
          <mesh
            geometry={nodes.L_handle_aiStandardSurface1_0.geometry}
            material={nodes.L_handle_aiStandardSurface1_0.material}
          />
          <group
            position={[-0.76, 0, 0]}
            rotation={[-Math.PI, 0, 0]}
            scale={-1}
          >
            <mesh
              geometry={nodes.R_handle_aiStandardSurface1_0.geometry}
              material={nodes.R_handle_aiStandardSurface1_0.material}
            />
          </group>
          <mesh
            geometry={nodes.polySurface24_aiStandardSurface1_0.geometry}
            material={nodes.polySurface24_aiStandardSurface1_0.material}
          />
          <mesh
            geometry={nodes.polySurface43_aiStandardSurface1_0.geometry}
            material={nodes.polySurface43_aiStandardSurface1_0.material}
          />
          <mesh
            geometry={nodes.wheel_aiStandardSurface1_0.geometry}
            material={nodes.wheel_aiStandardSurface1_0.material}
          />
          <group position={[0.32, 0, -1.27]} rotation={[0, Math.PI / 2, 0]}>
            <mesh
              geometry={nodes.wheel2_aiStandardSurface1_0.geometry}
              material={nodes.wheel2_aiStandardSurface1_0.material}
            />
          </group>
          <group position={[-1.27, 0, -0.32]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh
              geometry={nodes.wheel3_aiStandardSurface1_0.geometry}
              material={nodes.wheel3_aiStandardSurface1_0.material}
            />
          </group>
          <group
            position={[-0.96, 0, -1.59]}
            rotation={[-Math.PI, 0, -Math.PI]}
          >
            <mesh
              geometry={nodes.wheel4_aiStandardSurface1_0.geometry}
              material={nodes.wheel4_aiStandardSurface1_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/coolroom3.glb");
