/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/djbooth.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.7}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-3.06, 0.96, 3.8]} rotation={[-Math.PI, 0, -Math.PI]}>
            <group position={[0.02, 1.36, -0.77]} rotation={[-0.79, 0, 0]}>
              <mesh geometry={nodes.Mesh_13.geometry} material={nodes.Mesh_13.material} />
            </group>
            <group position={[0.69, 1.36, -0.77]} rotation={[-0.79, 0, 0]}>
              <mesh geometry={nodes.Mesh_11.geometry} material={nodes.Mesh_11.material} />
            </group>
            <group position={[0.36, 1.36, -0.77]} rotation={[-0.79, 0, 0]}>
              <mesh geometry={nodes.Mesh_10.geometry} material={nodes.Mesh_10.material} />
            </group>
            <group position={[1.04, 1.05, -0.9]}>
              <mesh geometry={nodes.Mesh_0.geometry} material={nodes.Mesh_0.material} />
              <group position={[0, 0.1, -0.04]}>
                <mesh geometry={nodes.Mesh_1.geometry} material={nodes.Mesh_1.material} />
              </group>
              <group position={[-0.13, 0.1, -0.05]}>
                <mesh geometry={nodes.Mesh_2.geometry} material={nodes.Mesh_2.material} />
              </group>
              <group position={[-0.13, 0.11, 0.08]}>
                <mesh geometry={nodes.Mesh_3.geometry} material={nodes.Mesh_3.material} />
              </group>
              <group position={[-0.08, 0.11, 0.13]}>
                <mesh geometry={nodes.Mesh_4.geometry} material={nodes.Mesh_4.material} />
              </group>
            </group>
            <group position={[-0.8, 1.05, -0.96]} rotation={[0, -0.6, 0]}>
              <mesh geometry={nodes.Mesh_5.geometry} material={materials.DJControl02} />
            </group>
            <group position={[0.35, 1.05, -0.79]}>
              <mesh geometry={nodes.Mesh_12.geometry} material={materials.DJControlHolder01} />
            </group>
            <group position={[1.71, 1.05, -1.3]} rotation={[0, 0.81, 0]}>
              <mesh geometry={nodes.Mesh_7.geometry} material={materials.DJMidiKeyboard01} />
            </group>
            <group position={[0.3, 0.15, -1.5]} rotation={[Math.PI, 0, Math.PI]}>
              <mesh geometry={nodes.Mesh_8.geometry} material={materials.DJTable01} />
            </group>
            <group position={[-1.33, 1.05, -1.5]} rotation={[0, -0.88, 0]}>
              <mesh geometry={nodes.Mesh_6.geometry} material={materials.DMXController01} />
            </group>
            <group position={[1.36, 1.16, -1.27]}>
              <mesh geometry={nodes.Mesh_9.geometry} material={materials.Headphones01} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/djbooth.glb')
