/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/door3.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group position={[46.92, 95.31, 0]} rotation={[0, 0, -Math.PI]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              position={[10.95, 17.48, -21.86]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <group name="door_left" position={[0.1, 1.65, 7.01]}>
                <mesh
                  geometry={nodes.door_left_door_0.geometry}
                  material={nodes.door_left_door_0.material}
                />
              </group>
              <group position={[0.1, -1.62, 6.84]}>
                <mesh
                  geometry={nodes.door_right_door_0.geometry}
                  material={nodes.door_right_door_0.material}
                />
              </group>
              <group position={[-2.48, -5.48, 7.52]} scale={[0.23, 0.73, 0.73]}>
                <mesh
                  geometry={nodes.door_controls_door_0.geometry}
                  material={nodes.door_controls_door_0.material}
                />
              </group>
              <group
                position={[2.73, 5.94, 7.52]}
                rotation={[0, 0, -Math.PI]}
                scale={[0.23, 0.73, 0.73]}
              >
                <mesh
                  geometry={nodes.door_controls_back_door_0.geometry}
                  material={nodes.door_controls_back_door_0.material}
                />
              </group>
              <group position={[0.12, 0.4, -0.07]} scale={22.72}>
                <mesh
                  geometry={nodes.door_outer_door_0.geometry}
                  material={nodes.door_outer_door_0.material}
                />
              </group>
              <group
                position={[-0.01, 0.11, -0.07]}
                rotation={[0, 0, -Math.PI]}
                scale={22.72}
              >
                <mesh
                  geometry={nodes.door_outer_back_door_0.geometry}
                  material={nodes.door_outer_back_door_0.material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/door3.glb");
