/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/futureBed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-71.27, 50, 0.63]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Almohada_Almohada_0.geometry} material={materials.Almohada} />
          </group>
          <group position={[0, 15, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Base_Basee_0.geometry} material={materials.Basee} />
          </group>
          <group position={[0, 40.1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[97, 48.5, 97]}>
            <mesh geometry={nodes.Colchon_Colchon_0.geometry} material={materials.Colchon} />
          </group>
          <group position={[-64.25, 28, 92.68]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[35, 35, 28]}>
            <mesh geometry={nodes.Mueble1_Mueble_0.geometry} material={nodes.Mueble1_Mueble_0.material} />
          </group>
          <group position={[-64.25, 28, 92.68]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[35, 35, 28]}>
            <mesh geometry={nodes.Mueble1001_Mueble001_0.geometry} material={nodes.Mueble1001_Mueble001_0.material} />
          </group>
          <group position={[-64.82, 28, -92.68]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[35, 35, 28]}>
            <mesh geometry={nodes.Mueble2_Mueble_0.geometry} material={nodes.Mueble2_Mueble_0.material} />
          </group>
          <group position={[-64.82, 28, -92.68]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[35, 35, 28]}>
            <mesh geometry={nodes.Mueble2001_Mueble001_0.geometry} material={nodes.Mueble2001_Mueble001_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/futureBed.glb')
