/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/golfClock.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-7.41, 4.43, -0.34]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.pCube12_lambert1_0.geometry} material={materials.lambert1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/golfClock.glb')
