/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/guitar.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Material2.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Material2001.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Material2003.geometry} material={materials.material_11} />
        <mesh geometry={nodes.Material3.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Material3001.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Material3002.geometry} material={materials.black} />
        <mesh geometry={nodes.Material3003.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Material3004.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Material3005.geometry} material={materials.material_10} />
        <mesh geometry={nodes.Material3006.geometry} material={materials.material_8} />
      </group>
    </group>
  )
}

useGLTF.preload('/guitar.glb')
