/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/hoop.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.47}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI, 0, -Math.PI]}>
            <group position={[-6.72, -2.29, -15.28]} rotation={[0, 1.57, 0]}>
              <mesh geometry={nodes.Mesh_0.geometry} material={materials.mat_HoopPole01} />
              <mesh geometry={nodes.Mesh_1.geometry} material={materials.mat_HoopScrews01} />
              <mesh geometry={nodes.Mesh_2.geometry} material={materials.mat_HoopBorder01} />
              <mesh geometry={nodes.Mesh_3.geometry} material={materials.mat_HoopGlass01} />
              <mesh geometry={nodes.Mesh_4.geometry} material={materials.mat_HoopLine01} />
              <mesh geometry={nodes.Mesh_5.geometry} material={materials.mat_Hoop01} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hoop.glb')
