/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/hoverCar.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Armature|Pose_0_Gravity"].play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_25.geometry}
              material={materials.Mat_Base}
              skeleton={nodes.Object_25.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_26.geometry}
              material={materials.Mat_Motor}
              skeleton={nodes.Object_26.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_27.geometry}
              material={materials.Mat_Int}
              skeleton={nodes.Object_27.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_28.geometry}
              material={materials.Mat_Cristal}
              skeleton={nodes.Object_28.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_29.geometry}
              material={materials.Mat_black_w}
              skeleton={nodes.Object_29.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_30.geometry}
              material={materials.Mat_LuzB}
              skeleton={nodes.Object_30.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_31.geometry}
              material={materials.Mat_LuzR}
              skeleton={nodes.Object_31.skeleton}
            />
          </group>
          <group position={[297.41, 544.56, 496.46]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/hoverCar.glb");
