/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lambo.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Lamborghini-text-logo-1440x900']} />
        <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
        <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
        <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
        <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
        <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
        <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
        <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
        <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
        <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
        <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
        <mesh geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
        <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
        <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
        <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
        <mesh geometry={nodes.Object_35.geometry} material={nodes.Object_35.material} />
        <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
        <mesh geometry={nodes.Object_37.geometry} material={nodes.Object_37.material} />
        <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
        <mesh geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.018']} />
      </group>
    </group>
  )
}

useGLTF.preload('/lambo.glb')
