/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/nightClub.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[113.07, 82.24, 3.5]}>
            <group position={[-300.15, -185.55, 67.41]}>
              <mesh geometry={nodes.Bar_2__0.geometry} material={materials.Bar_2__0} />
              <mesh geometry={nodes.Bar_2_Mat1_0.geometry} material={materials['Mat.1']} />
              <mesh geometry={nodes.Bar_2_Mat2_0.geometry} material={materials['Mat.2']} />
              <mesh geometry={nodes.Bar_2_Mat2_0001.geometry} material={materials['Mat.2_0']} />
              <mesh geometry={nodes.Bar_2_Mat3_0.geometry} material={materials['Mat.3']} />
              <mesh geometry={nodes.Bar_2_Mat4_0.geometry} material={materials['Mat.4']} />
              <mesh geometry={nodes.Bar_2_Mat4_0001.geometry} material={materials['Mat.4_0']} />
              <mesh geometry={nodes.Bar_2_Mat4_0002.geometry} material={materials['Mat.4_1']} />
              <mesh geometry={nodes.Bar_2_Mat4_0003.geometry} material={materials['Mat.4_2']} />
              <mesh geometry={nodes.Bar_2_Mat4_0004.geometry} material={materials['Mat.4_3']} />
              <mesh geometry={nodes.Bar_2_Mat4_0005.geometry} material={materials['Mat.4_4']} />
              <mesh geometry={nodes.Bar_2_Mat5_0.geometry} material={materials['Mat.5']} />
              <mesh geometry={nodes.Bar_2_Mat6_0.geometry} material={materials['Mat.6']} />
              <mesh geometry={nodes.Bar_2_Mat_0.geometry} material={materials.material} />
            </group>
            <group position={[-85.88, 46.39, -208.34]}>
              <mesh geometry={nodes.tube_Mat7_0.geometry} material={nodes.tube_Mat7_0.material} />
            </group>
            <group position={[234.57, 46.39, -208.34]}>
              <mesh geometry={nodes.tube_1_Mat7_0.geometry} material={nodes.tube_1_Mat7_0.material} />
            </group>
            <group position={[-85.88, 46.39, 174.63]}>
              <mesh geometry={nodes.tube_2_Mat7_0.geometry} material={nodes.tube_2_Mat7_0.material} />
            </group>
            <group position={[237.34, 46.39, 174.63]}>
              <mesh geometry={nodes.tube_3_Mat7_0.geometry} material={nodes.tube_3_Mat7_0.material} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/nightClub.glb')
