/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/office.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group position={[430.45, 581.92, 73.9]} rotation={[1.46, 0.08, 0.01]} />
        <mesh geometry={nodes.Material2.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Material2001.geometry} material={materials.Structure} />
        <mesh geometry={nodes.Material2002.geometry} material={nodes.Material2002.material} />
        <mesh geometry={nodes.Material2003.geometry} material={nodes.Material2003.material} />
        <mesh geometry={nodes.Material2004.geometry} material={materials.Long_Walls} />
        <mesh geometry={nodes.Material2005.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Material2006.geometry} material={materials.Walls} />
        <mesh geometry={nodes.Material2007.geometry} material={materials.Wall_Horizon} />
        <mesh geometry={nodes.Material2008.geometry} material={materials.Red_Lamp} />
        <mesh geometry={nodes.Material3001.geometry} material={nodes.Material3001.material} />
        <mesh geometry={nodes.Material3002.geometry} material={nodes.Material3002.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/office.glb')
