/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/planets2.glb");
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-2.41, 0, 0]} scale={[-0.01, -0.01, -0.01]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            name="Asteroid"
            position={[-339.23, 452.48, 846.15]}
            rotation={[-0.65, 0, 0]}
            scale={[9.92, 8.63, 11.12]}
          >
            <mesh
              geometry={nodes.Asteroid_ASTEROID_0.geometry}
              material={materials.ASTEROID}
            />
          </group>
          <group rotation={[0, 0, 0.35]} scale={9.12}>
            <group position={[27.12, 0.01, -0.07]} scale={0.2}>
              <mesh
                geometry={nodes.Moon1_MOON_0.geometry}
                material={materials.MOON}
              />
            </group>
            <mesh
              geometry={nodes.Earth1_EARTH_0.geometry}
              material={materials.EARTH}
            />
          </group>
          <group scale={22.44}>
            <mesh
              geometry={nodes.Jupiter1_JUPITER_0.geometry}
              material={materials.JUPITER}
            />
          </group>
          <group rotation={[0, 0, -0.52]} scale={6.86}>
            <mesh
              geometry={nodes.Mars1_MARS_0.geometry}
              material={materials.MARS}
            />
          </group>
          <group rotation={[0, 0, 1.24]} scale={4.92}>
            <mesh
              geometry={nodes.Mercury1_MERCURY_0.geometry}
              material={materials.MERCURY}
            />
          </group>
          <group rotation={[0, 0, 0.97]} scale={11.04}>
            <mesh
              geometry={nodes.Neptune1_NEPTUNE_0.geometry}
              material={materials.NEPTUNE}
            />
          </group>
          <group rotation={[0, 0, 1.36]} scale={4.32}>
            <mesh
              geometry={nodes.Pluto1_PLUTO_0.geometry}
              material={materials.PLUTO}
            />
          </group>
          <group rotation={[0, 0, 0.4]}>
            <mesh
              geometry={nodes.pTorus1_RINGS_0.geometry}
              material={nodes.pTorus1_RINGS_0.material}
            />
            <mesh
              geometry={nodes.Rings1_RINGS_0.geometry}
              material={nodes.Rings1_RINGS_0.material}
            />
            <mesh
              geometry={nodes.Saturn1_SATURN_0.geometry}
              material={materials.SATURN}
            />
          </group>
          <mesh
            geometry={nodes.Sun_SUN_0.geometry}
            material={materials.material}
          />
          <group rotation={[0, 0, -0.08]} scale={11.04}>
            <mesh
              geometry={nodes.Uranus1_URANUS_0.geometry}
              material={materials.URANUS}
            />
          </group>
          <group rotation={[0, 0, -0.41]} scale={6.86}>
            <mesh
              geometry={nodes.Venus1_VENUS_0.geometry}
              material={materials.VENUS}
            />
          </group>
          <group scale={142.39}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group scale={2679.07}>
            <mesh
              geometry={nodes.BG_BG2_0.geometry}
              material={materials.material_16}
            />
          </group>
          <group position={[27.77, -0.82, 21.05]} rotation={[0, 0.11, 0]}>
            <mesh
              geometry={nodes.Flame_FLAME_0.geometry}
              material={materials.FLAME}
            />
            <mesh
              geometry={nodes.RocketBody_BODY_0.geometry}
              material={materials.BODY}
            />
            <mesh
              geometry={nodes.ROcketLeg_LEG_0.geometry}
              material={nodes.ROcketLeg_LEG_0.material}
            />
            <mesh
              geometry={nodes.RocketLeg2_LEG_0.geometry}
              material={nodes.RocketLeg2_LEG_0.material}
            />
            <mesh
              geometry={nodes.RocketLeg3_LEG_0.geometry}
              material={nodes.RocketLeg3_LEG_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/planets2.glb");
