/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/stereo.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group scale={0.26}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[626, 853.7, 548.79]} rotation={[Math.PI, 0.76, 2.68]} scale={[100, 100, 100]} />
            <group position={[34.05, 347.3, 137.66]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh geometry={nodes.Stereo_SM_Material014_0.geometry} material={materials['Material.014']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/stereo.glb')
