/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/vendingMachine.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Take 001"].play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_6.geometry}
            material={materials.lambert1}
            skeleton={nodes.Object_6.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_7.geometry}
            material={materials.lambert2}
            skeleton={nodes.Object_7.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/vendingMachine.glb");
